# Base image.
FROM python:3.14-slim-trixie

# Install system dependencies (drivers)
# Ye command "pyodbc" ke liye zaroori drivers install karega
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gnupg2 \
       curl \
       apt-transport-https \
       unixodbc-dev \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
    && rm -rf /var/lib/apt/lists/*

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Working directory set karein.
WORKDIR /app

# Add code and install dependencies using a staged approach.
# Dependencies install karein uv.lock file se.
COPY uv.lock .
COPY pyproject.toml .
# --locked flag se ye ensure hota hai ke sirf wohi versions install hon jo lock file mein hain.
RUN uv sync --locked

# Ab baki ka application code copy karein.
COPY . .

# Default port expose karein.
EXPOSE 8000

# Application run karein.
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port","8000"]
